### ISSUE TITLE
Error on loading val_dataset. 

### ISSUE THREAD

**Issue by Dean-UQ** [EricGuo5513/text-to-motion#1]
Hi Guo,

 Thank you for sharing the official codes. I followed the instructions in the README.md and copy the HumanML3D dataset from [here](https://github.com/EricGuo5513/HumanML3D/tree/main/HumanML3D) directly. However, when I tried to run the train_decomp_v3.py, I met an error shown in Fig.1.  I would like to know what makes this error and how to fix it.

Many thanks for your help.
![2022-06-14 21-20-10屏幕截图](https://user-images.githubusercontent.com/97895595/173591893-09c683de-0cb1-420f-9e9d-28ac8ac86255.png)

**Comment by EricGuo5513** [comment]
Would you mind giving me a message if you successfully go through the HumanML3D repository? I will appreciate it so much.

**Comment by Dean-UQ** [comment]
No problem, I will.
