### ISSUE TITLE
About the comparative experiment

### ISSUE THREAD

**Issue by zhuangzhuang000** [EricGuo5513/text-to-motion#10]
Dear author:
       The motion input of your work is 263 dimensions, may I ask if you changed the input of other methods to 263 dimensions and retrained other methods on the HumanML3D dataset when you did the comparison experiment with other methods?

**Comment by EricGuo5513** [comment]
Hi,

Yes, for all baselines we use the 263-dim pose representation. We retrained
their methods.

Best,

Chuan
