### ISSUE TITLE
Time to arrival 

### ISSUE THREAD

**Issue by yonishafir** [EricGuo5513/text-to-motion#11]
It seems to me that you use positional encoding, although in the paper you mention to use time to arrival.

Could you please forward to where you implement and use time to arrival positional encoding?

**Comment by EricGuo5513** [comment]
https://github.com/EricGuo5513/text-to-motion/blob/main/networks/trainers.py#:~:text=%2D1%5D)-,tta%20%3D%20m_lens%20//%20self.opt.unit_length%20%2D%20i,-if%20self.

Hi, please check here.

**Comment by yonishafir** [comment]
I could not find the line where your'e using time to arrival in the above reference.

instead I see both in:
https://github.com/EricGuo5513/text-to-motion/blob/main/networks/modules.py#L43

and in:
https://github.com/EricGuo5513/text-to-motion/blob/main/networks/modules.py#L62

Positional encoding (forward).

I'll be happy for a better reference.

thanks

**Comment by EricGuo5513** [comment]
Hi, the time-to-arrival is technically implemented by positional encoding. While the difference is that, usually people would feed the current time step t for positional encoding, our time-to-arrival feed T-t for positional encoding, where T is the target length and t is the current time step. This could make the model know how long the generation process is yet to be done.

**Comment by yonishafir** [comment]
Thanks for the detailed answer, I couldn't find where you feed  your model positional encoding with t=T-t (instead of t)
can you please kindly direct me to the correct line in the trainer?

**Comment by EricGuo5513** [comment]
It is here: https://github.com/EricGuo5513/text-to-motion/blob/main/networks/trainers.py#:~:text=%2D1%5D)-,tta%20%3D%20m_lens%20//%20self.opt.unit_length%20%2D%20i,-if%20self

**Comment by EricGuo5513** [comment]
It is at the line 334 in https://github.com/EricGuo5513/text-to-motion/blob/main/networks/trainers.py.

**Comment by yonishafir** [comment]
Thanks a lot
