### ISSUE TITLE
Licensing questions

### ISSUE THREAD

**Issue by pkpro** [EricGuo5513/text-to-motion#13]
Hello @EricGuo5513 ,
1. There is no mentioning of the license in this repository. Can you please fill this gap in?
2. Do I assume correctly that you store the data in SMPL format and related SMPL software should be used to convert it to any other format, thus applying the license of SMPL-Body or equivalent derivative?
3. Are any of derivatives of the SMPL-Model have been used in your code, thus applying the license of the SMPL-Model as well?

Thanks in advance,
pk

**Comment by EricGuo5513** [comment]
Hi,

Thanks for the reminder. The license has been created. For text2motion, no SMPL related model has been used. Also using text2motion do not necessarily involve SMPL or related derivatives. Our data format is not in SMPL format. Therefore, the license of text2motion repos is independent with SMPL license.

**Comment by pkpro** [comment]
@EricGuo5513 Thanks a lot for the answers!
