### ISSUE TITLE
Do we need to load the pretrained checkpoints when training the feature extractor?

### ISSUE THREAD

**Issue by linjing7** [EricGuo5513/text-to-motion#15]
Hi, I use a different motion representation from HumanML3D, and thus I need to train a new feature extractor for evaluation. I run the following command:
`python train_tex_mot_match.py --name text_mot_match --gpu_id 1 --batch_size 8 --dataset_name t2m`
But an error occurs because I need to load the pretrained checkpoint. Do I need to train a new motion autoencoder before training the feature extraction network?
<img width="931" alt="image" src="https://user-images.githubusercontent.com/70081899/212461910-ab2a53d4-1476-4ae3-9d0d-d839c8618bd5.png">

**Comment by EricGuo5513** [comment]
Hi, for text_mot_match model, our model require a preliminary autoencoder to extract high level feature. This can reduce the sequence length. But if you are training your own text_mot_match model, you may skip this and directly feed raw pose sequence. This is up to you.

**Comment by linjing7** [comment]
Okay, thanks for your reply!
