### ISSUE TITLE
How to implement SMPL skin model?

### ISSUE THREAD

**Issue by fyyakaxyy** [EricGuo5513/text-to-motion#16]
Hello

First of all thank you very much for posting this repository.

The result of my reproduction is a skeleton model of the human body, how should the SMPL skin model shown in your project be realized?

Thanks in advance！

**Comment by EricGuo5513** [comment]
Hello, please check this issue: https://github.com/EricGuo5513/HumanML3D/issues/1. I also recommend you to look in the git of [MDM](https://github.com/GuyTevet/motion-diffusion-model) and [TEMOS](https://github.com/Mathux/TEMOS). They use blender and have good visualization results.

**Comment by fyyakaxyy** [comment]
Thank you very much for your answer. With your help, my problem has been solved!

**Comment by Jolinbaby** [comment]
> Thank you very much for your answer. With your help, my problem has been solved!

Hi～Could you please tell me what method you used to render the motions?
