### ISSUE TITLE
Foot Contact for KIT

### ISSUE THREAD

**Issue by exitudio** [EricGuo5513/text-to-motion#17]
Thank you for all your amazing work.
My KIT visualization looks weird. 
1. Feet are moving
2. Hands are behind
Have you seen the same issues? Are these issues from the raw data itself?
![Animation](https://user-images.githubusercontent.com/3590976/219253539-09e02fd6-8ae7-4a02-b5f9-da7fed23075b.gif)

**Comment by EricGuo5513** [comment]
Hi,

I obtained the KIT data from the git repository of Language2Pose. My
visualizations are also like this.

**Comment by exitudio** [comment]
Thank you for your information.
