### ISSUE TITLE
Generating results for the KIT ML dataset

### ISSUE THREAD

**Issue by Rusali28** [EricGuo5513/text-to-motion#2]
Hello, 
Can you kindly explain how can we get the sampling results for the KITML dataset? The instructions in the repo are for the HumanML3D

**Comment by EricGuo5513** [comment]
Hi, sorry for KITML dataset, we only report the quantitative results as in "final_evaluation.py". To visualize the sampled results, you may need to modify the eval_comp_v6.py or gen_motion_script.py with loading the models for KIT-ML dataset and configurations as below:

    elif opt.dataset_name == 'kit':
        opt.data_root = './dataset/KIT-ML'
        opt.motion_dir = pjoin(opt.data_root, 'new_joint_vecs')
        opt.text_dir = pjoin(opt.data_root, 'texts')
        opt.joints_num = 21
        radius = 240 * 8
        fps = 12.5
        dim_pose = 251
        opt.max_motion_length = 196
        kinematic_chain = paramUtil.kit_kinematic_chain
