### ISSUE TITLE
Fixing the length of generated motion

### ISSUE THREAD

**Issue by AkbarShah96** [EricGuo5513/text-to-motion#22]
Hi, is it possible to fix the length of the generated motion in gen_motion_script.py?

Thanks!

**Comment by EricGuo5513** [comment]
You could just skip the estimate_length part, and feed the lengths as you
want.

**Comment by KrispyNoodles** [comment]
![Image](https://github.com/user-attachments/assets/17fbd714-4490-431d-94a7-3f8043ffd1b6)

can I ask how can I replace this parameter to increase the length of the generated motion then?
