### ISSUE TITLE
Can't set attribute in plot_3d_motion function

### ISSUE THREAD

**Issue by StefanoBraghetto** [EricGuo5513/text-to-motion#23]
Hello,

please your help with an error that tried to solve but couldn't.

in line 81 of your code in plot_3d_motion function an error appears:

  -->      ax.lines = []
        ax.collections = []
        ax.view_init(elev=120, azim=-90)
        ax.dist = 7.5

AttributeError: can't set attribute

could you please help me to solve it. This function uses FuncAnimation of matplotlib to create a fast animation of the character.

Thank you!

**Comment by EricGuo5513** [comment]
Hi,

Maybe you could try different matplotlib version. I guess you are using the
latest version. Try the version indicated in our git.

**Comment by StefanoBraghetto** [comment]
Solved.

Sorry for the basic question. Thanks!!!

**Comment by StefanoBraghetto** [comment]
Solved
