### ISSUE TITLE
About the confidence of generated results

### ISSUE THREAD

**Issue by lzyplayer** [EricGuo5513/text-to-motion#24]
Thanks for such great work!
Is there a numerical value that can represent the confidence of the generated result pose motion?
And It would be great if you could explain the return value.
For example, the function `generate` in trainers.py 384 returns `fake_motions, mus_pri, att_wgts`. Could you please explain them a little bit?

**Comment by EricGuo5513** [comment]
Hi, not sure about the confidence you refer to. Do you mean the reported confidence value in our paper? We calculate the 95% confidence in https://github.com/EricGuo5513/text-to-motion/blob/main/final_evaluations.py#:~:text=def-,get_metric_statistics,-(values)%3A.

In generate function, fake motions are exactly the generated motions, mus_pri and attwgts are only for analysis during the inference process.

**Comment by lzyplayer** [comment]
Thanks for your help! 
Then I assume that the motion sequences generated multiple times are equally loyal to the input in the algorithm, am I right?

**Comment by EricGuo5513** [comment]
Yes, it is correct.
