### ISSUE TITLE
How to obtain glove?

### ISSUE THREAD

**Issue by ZhengdiYu** [EricGuo5513/text-to-motion#35]
Thank you for your amazing work! May I ask how we can obtain `glove`? It seems like some vocab and a 300-dim word vector. Where can we get the 300 dim vectors? (e.g. if we want to enlarge the vocab or change to another language)

**Comment by EricGuo5513** [comment]
Hi, I got it from https://nlp.stanford.edu/projects/glove/, specifically this one: https://nlp.stanford.edu/data/glove.6B.zip.

**Comment by ZhengdiYu** [comment]
Great! Exactly the same one as I found before. :) Thank you for confirming.
