### ISSUE TITLE
How to convert the final generated 2D animation into the 3D form in the paper？

### ISSUE THREAD

**Issue by 24kbijin** [EricGuo5513/text-to-motion#4]
This is a very rewarding and outstanding job!
Using the code you provided I have successfully implemented the resulting output
But I want  to know **how to convert the final generated 2D animation into the 3D form in the paper？**

Looking forward your reply!
Best wishes!

**Comment by EricGuo5513** [comment]
Hi, there is a related issue which may help you: https://github.com/EricGuo5513/HumanML3D/issues/1
