### ISSUE TITLE
Work slides presentation

### ISSUE THREAD

**Issue by BrianG13** [EricGuo5513/text-to-motion#5]
Hi guys,

Your work is super interesting and exciting!

I am wondering if you maybe have a slides presentation (PowerPoint file) already prepared? I want to present your paper at my work :) 

Thanks!

**Comment by EricGuo5513** [comment]
Hi, thanks for your interests. This is the powerpoint file for our demo video. Hope it works for you. https://docs.google.com/presentation/d/1s25Pih1gk9Y2Y5uHR6PLudTlpH7KFyZ2/edit?usp=sharing&ouid=101899616177909092432&rtpof=true&sd=true
