### ISSUE TITLE
how can I get the KIT-ML dataset?

### ISSUE THREAD

**Issue by eanson023** [EricGuo5513/text-to-motion#9]
I used this [HumanML3D](https://github.com/EricGuo5513/HumanML3D) to obtain data, but it only generated the HumanML3D directory and the KIT-ML directory that this project needed was not found

**Comment by EricGuo5513** [comment]
You can directly download the KIT dataset from the HumanML3D webpage.

Best,

Chuan

**Comment by eanson023** [comment]
Thank you, I understand what you mean

**Comment by eanson023** [comment]
Dear Dr. Guo,

Is there a series of scripts that processed the original  KIT-ML dataset, I want to learn how different progress process the original KIT-ML dataset compared with [TEMOS](https://github.com/Mathux/TEMOS). And I have another question, is there an explanation of how to process human skeletons(such as  Skeleton-based representation(MMM framework), SMPL-based representation) on the Internet? 😭

Thank you in advance for any help you might be able to provide.

Sincerely,

Eanson

**Comment by EricGuo5513** [comment]
Hi Eason,

I didn't process the original MMM-format data of KIT-ML. I use the github
repository of https://github.com/chahuja/language2pose to extract 3D
positions of joint, and then use the motion_representation.ipynb to obtain
our KIT-ML data.

Best,

Chuan

eanson023 ***@***.***> 于2022年11月29日周二 19:50写道：
